#!/usr/bin/env python3
"""Vendor the Google Fonts the UI uses into each frontend's public/fonts/.

The app must render on an isolated workshop network, so nothing may be
fetched from fonts.googleapis.com at runtime. This pulls the *variable*
woff2 files (one per family per subset) and writes a fonts.css with
relative urls, which index.html links instead of the Google stylesheet.

Only the latin and latin-ext subsets are kept; the UI is English-only.

Re-run after changing which families/weights style.css uses:
    python tools/fetch_fonts.py
"""

import re
import subprocess
import sys
from pathlib import Path

# Matches the families/weights the two index.html files used to request.
CSS_URL = (
    "https://fonts.googleapis.com/css2"
    "?family=Inter:wght@300..700&family=Outfit:wght@500..700&display=swap"
)

# Without a modern UA, Google serves static TTF instead of variable woff2.
UA = (
    "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 "
    "(KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36"
)

KEEP_SUBSETS = ("latin", "latin-ext")

TARGETS = [
    Path("frontend/public/fonts"),
    Path("frontend-radar/public/fonts"),
]

HEADER = """/* Self-hosted Google Fonts (Inter, Outfit) - variable woff2.
   Vendored so the UI renders with no internet access.
   Generated by tools/fetch_fonts.py - do not edit by hand. */
"""


def curl(url, dest=None):
    # --ssl-no-revoke: some corporate Windows boxes cannot reach the CRL
    # endpoint for gstatic and fail the handshake without it.
    cmd = ["curl", "-fsS", "--ssl-no-revoke", "-A", UA, url]
    if dest:
        cmd += ["-o", str(dest)]
        subprocess.run(cmd, check=True)
        return None
    return subprocess.run(cmd, check=True, capture_output=True, text=True).stdout


def main():
    print(f"Fetching font stylesheet...")
    css = curl(CSS_URL)

    blocks = re.findall(r"/\* ([a-z-]+) \*/\s*(@font-face \{.*?\})", css, re.S)
    keep = [(s, b) for s, b in blocks if s in KEEP_SUBSETS]
    if not keep:
        print("  ERROR: no matching @font-face blocks; did the API change?")
        return 1
    print(f"  {len(blocks)} blocks returned, keeping {len(keep)}")

    primary = TARGETS[0]
    primary.mkdir(parents=True, exist_ok=True)

    out = [HEADER]
    for subset, block in keep:
        url = re.search(r"url\((https://[^)]+\.woff2)\)", block).group(1)
        family = re.search(r"font-family: '([^']+)'", block).group(1)
        name = f"{family.lower()}-{subset}.woff2"
        curl(url, primary / name)
        print(f"  {name}  {(primary / name).stat().st_size:,} bytes")
        out.append(f"/* {subset} */")
        out.append(block.replace(url, f"./{name}"))
        out.append("")

    (primary / "fonts.css").write_text("\n".join(out) + "\n",
                                       encoding="utf-8", newline="\n")
    print(f"  wrote {primary / 'fonts.css'}")

    # Both frontends share the same font set; mirror rather than re-download.
    for mirror in TARGETS[1:]:
        if not mirror.parent.parent.exists():
            print(f"  skip {mirror}: frontend not present")
            continue
        mirror.mkdir(parents=True, exist_ok=True)
        for src in sorted(primary.iterdir()):
            (mirror / src.name).write_bytes(src.read_bytes())
        print(f"  mirrored to {mirror}")

    return 0


if __name__ == "__main__":
    sys.exit(main())
